php-version = "8.5.0"

[source]
workspace = "."
paths = ["src/"]
includes = ["vendor"]
excludes = ["src/Twig/Extensions"]

[formatter]
print-width = 130
tab-width = 4
use-tabs = false
method-brace-style = "always-next-line"
space-around-concatenation-binary-operator = true
trailing-comma = false

[linter]
integrations = ["phpunit", "tempest"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-else-clause = { enabled = false }
cyclomatic-complexity = { threshold = 20 }
excessive-parameter-list = { enabled = false }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true