name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: Audit dependencies
        run: composer audit --locked

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: Restore Composer cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Check code format
        run: vendor/bin/mago format --check || vendor/bin/mago format --dry-run

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: Restore Composer cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Check the code style
        run: composer lint

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer

      - name: Restore the Composer cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Run tests
        run: composer test
